### ISSUE TITLE
Bug: Nach dem stoppen der Aufnahme, Aufnahme Dropdown bleibt disabled

### ISSUE THREAD

**Issue by ideadapt** [bendsoft/MultitrackRecorderUI#2]

**Comment by bendsoft** [comment]
It's not a bug, it's a feature :)

Solange man nicht mehr als 1 Aufnahme im dropdown hat, bleibt es disabled. Man kann jetzt darüber diskuttieren, ob das intuitiv ist, oder nicht ;)
